name: english_vip
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  dots_indicator: ^1.2.0
  youtube_player_flutter: ^7.0.0+7
  countup: ^0.1.3
  shared_preferences: ^2.0.3
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  another_flushbar: ^1.10.15
  firebase_storage: ^8.0.0
  easy_dialog: ^1.0.5
  rxdart: 0.22.6
  cool_alert: ^1.0.3
  flutter_credit_card: ^0.1.4
  stripe_payment: ^1.0.10
  http: ^0.13.0
  intl_phone_field: ^1.4.4
  firebase_messaging: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
      - images/

  fonts:
     - family: ScheherazadeBold
       fonts:
         - asset: fonts/ScheherazadeBold.ttf


     - family: ScheherazadeRegular
       fonts:
         - asset: fonts/ScheherazadeRegular.ttf

     - family: Custom
       fonts:
             - asset: fonts/Custom.ttf



